CREATE TABLE conta (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(255) NOT NULL,
    valor_original DECIMAL(19, 2) NOT NULL,
    data_vencimento DATE NOT NULL,
    data_pagamento DATE NOT NULL,
    valor_ajustado DECIMAL(19, 2) NOT NULL,
    dias_de_atraso INT NOT NULL
);